=== nivecher/carcassonne/src/main/xml/basic-tiles.xsd
<?xml version="1.0"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="urn:carcassonne:tiles"
           elementFormDefault="qualified"
           targetNamespace="urn:carcassonne:tiles">
    
    <xs:simpleType name="edge">
        <xs:restriction base="xs:string">
            <xs:enumeration value="north"/>
            <xs:enumeration value="east"/>
            <xs:enumeration value="south"/>
            <xs:enumeration value="west"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="edgeSegment">
        <xs:restriction base="xs:string">
            <xs:enumeration value="north-west"/>
            <xs:enumeration value="north-east"/>
            <xs:enumeration value="east-north"/>
            <xs:enumeration value="east-south"/>
            <xs:enumeration value="south-west"/>
            <xs:enumeration value="south-east"/>
            <xs:enumeration value="west-north"/>
            <xs:enumeration value="west-south"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:attributeGroup name="expansionAttributes">
        <xs:anyAttribute/>
    </xs:attributeGroup>

    <xs:group name="expansionGroup">
        <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:group>
    
    <xs:complexType name="feature" abstract="true">
        <xs:sequence>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
<!-- TODO       <xs:attributeGroup ref="tns:expansionAttributes"/>-->
    </xs:complexType>
    
    <xs:complexType name="segment" abstract="true">
        <xs:complexContent>
            <xs:extension base="tns:feature">
                <xs:choice>
                    <xs:element name="edge" type="tns:edge" minOccurs="0" maxOccurs="4"/>
                </xs:choice>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="city">
        <xs:complexContent>
            <xs:extension base="tns:segment">
                <xs:attribute name="pennants" type="xs:integer" default="0"/>
                <xs:attribute name="followers" fixed="knights"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="cloister">
        <xs:complexContent>
            <xs:extension base="tns:feature">
                <xs:attribute name="followers" fixed="monks"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="field">
        <xs:complexContent>
            <xs:extension base="tns:segment">
                <xs:sequence>
                    <xs:element name="edgeSegment" type="tns:edgeSegment" 
                                minOccurs="0" maxOccurs="8"/>
                </xs:sequence>
                <xs:attribute name="followers" fixed="farmers"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="road">
        <xs:complexContent>
            <xs:extension base="tns:segment">
                <xs:attribute name="followers" fixed="thieves"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="tile">
        <xs:annotation>
            <xs:documentation>
                Standard game tiles
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="city" type="tns:city" minOccurs="0" maxOccurs="4"/>
            <xs:element name="cloister" type="tns:cloister" minOccurs="0" maxOccurs="1"/>
            <xs:element name="field" type="tns:field" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="road" type="tns:road" minOccurs="0" maxOccurs="4"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="instances" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="tag" type="xs:string"/>
    </xs:complexType>
    
    <xs:element name="tileSet">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tile" type="tns:tile" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== nivecher/carcassonne/src/main/xml/basic-tiles.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:tileSet
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='urn:carcassonne:basic:tiles'
    xsi:schemaLocation='urn:carcassonne:basic:tiles basic-tiles.xsd'>
        
    <ns1:tile id="A" instances="2">
        <ns1:cloister/>
        <ns1:field>
            <ns1:edge>north</ns1:edge>
            <ns1:edge>east</ns1:edge>
            <ns1:edge>west</ns1:edge>
            <ns1:edgeSegment>south-east</ns1:edgeSegment>
            <ns1:edgeSegment>south-west</ns1:edgeSegment>
        </ns1:field>
        <ns1:road>
            <ns1:edge>south</ns1:edge>
        </ns1:road>
    </ns1:tile>
    <ns1:tile id="B" instances="4">
        <ns1:cloister/>
        <ns1:field>
            <ns1:edge>north</ns1:edge>
            <ns1:edge>east</ns1:edge>
            <ns1:edge>south</ns1:edge>
            <ns1:edge>west</ns1:edge>
        </ns1:field>
    </ns1:tile>
    <ns1:tile id="C" instances="1">
        <ns1:city>
            <ns1:edge>north</ns1:edge>
            <ns1:edge>east</ns1:edge>
            <ns1:edge>south</ns1:edge>
            <ns1:edge>west</ns1:edge>
            <ns1:pennant/>
        </ns1:city>
    </ns1:tile>
    <ns1:tile id="D" instances="4" description="Starting tile">
        <ns1:city>
            <ns1:edge>east</ns1:edge>
        </ns1:city>
        <ns1:field>
            <ns1:description>Field west of road</ns1:description>
            <ns1:edge>west</ns1:edge>
            <ns1:edgeSegment>north-west</ns1:edgeSegment>
            <ns1:edgeSegment>south-west</ns1:edgeSegment>
        </ns1:field>
        <ns1:field>
            <ns1:description>Field east of road</ns1:description>
            <ns1:edgeSegment>north-east</ns1:edgeSegment>
            <ns1:edgeSegment>south-east</ns1:edgeSegment>
        </ns1:field>
        <ns1:road>
            <ns1:edge>north</ns1:edge>
            <ns1:edge>south</ns1:edge>
        </ns1:road>
    </ns1:tile>
    <ns1:tile id="E" instances="5">
        <ns1:city>
            <ns1:edge>north</ns1:edge>
        </ns1:city>
        <ns1:field>
            <ns1:edge>east</ns1:edge>
            <ns1:edge>south</ns1:edge>
            <ns1:edge>west</ns1:edge>
        </ns1:field>
    </ns1:tile>
    <ns1:tile id="F" instances="2">
        <ns1:city>
            <ns1:edge>east</ns1:edge>
            <ns1:edge>west</ns1:edge>
            <ns1:pennant/>
        </ns1:city>
        <ns1:field>
            <ns1:edge>north</ns1:edge>
        </ns1:field>
        <ns1:field>
            <ns1:edge>south</ns1:edge>
        </ns1:field>
    </ns1:tile>
    <ns1:tile id="G" instances="1">
        <ns1:city>
            <ns1:edge>north</ns1:edge>
            <ns1:edge>south</ns1:edge>
        </ns1:city>
        <ns1:field>
            <ns1:edge>east</ns1:edge>
        </ns1:field>
        <ns1:field>
            <ns1:edge>west</ns1:edge>
        </ns1:field>
    </ns1:tile>
    <ns1:tile id="H" instances="3">
        <ns1:city>
            <ns1:edge>east</ns1:edge>
        </ns1:city>
        <ns1:city>
            <ns1:edge>west</ns1:edge>
        </ns1:city>
        <ns1:field>
            <ns1:edge>north</ns1:edge>
            <ns1:edge>south</ns1:edge>
        </ns1:field>
    </ns1:tile>
    <ns1:tile id="I" instances="2">
        <ns1:city>
            <ns1:edge>east</ns1:edge>
        </ns1:city>
        <ns1:city>
            <ns1:edge>south</ns1:edge>
        </ns1:city>
        <ns1:field>
            <ns1:edge>north</ns1:edge>
            <ns1:edge>west</ns1:edge>
        </ns1:field>
    </ns1:tile>
    <ns1:tile id="J" instances="3">
        <ns1:city>
            <ns1:edge>north</ns1:edge>
        </ns1:city>
        <ns1:field>
            <ns1:edge>west</ns1:edge>
            <ns1:edgeSegment>south-west</ns1:edgeSegment>
            <ns1:edgeSegment>east-north</ns1:edgeSegment>
        </ns1:field>
        <ns1:field>
            <ns1:edgeSegment>south-east</ns1:edgeSegment>
            <ns1:edgeSegment>east-south</ns1:edgeSegment>
        </ns1:field>
        <ns1:road>
            <ns1:edge>east</ns1:edge>
            <ns1:edge>south</ns1:edge>
        </ns1:road>
    </ns1:tile>
    <ns1:tile id="K" instances="3">
        <ns1:city>
            <ns1:edge>east</ns1:edge>
        </ns1:city>
        <ns1:field>
            <ns1:edgeSegment>west-north</ns1:edgeSegment>
            <ns1:edgeSegment>north-west</ns1:edgeSegment>
        </ns1:field>
        <ns1:field>
            <ns1:edge>south</ns1:edge>
            <ns1:edgeSegment>north-east</ns1:edgeSegment>
            <ns1:edgeSegment>west-south</ns1:edgeSegment>
        </ns1:field>
        <ns1:road>
            <ns1:edge>north</ns1:edge>
            <ns1:edge>west</ns1:edge>
        </ns1:road>
    </ns1:tile>
    <ns1:tile id="L" instances="3">
        <ns1:city>
            <ns1:edge>east</ns1:edge>
        </ns1:city>
        <ns1:field>
            <ns1:edgeSegment>west-north</ns1:edgeSegment>
            <ns1:edgeSegment>north-west</ns1:edgeSegment>
        </ns1:field>
        <ns1:field>
            <ns1:edgeSegment>north-east</ns1:edgeSegment>
            <ns1:edgeSegment>south-east</ns1:edgeSegment>
        </ns1:field>
        <ns1:field>
            <ns1:edgeSegment>west-south</ns1:edgeSegment>
            <ns1:edgeSegment>south-west</ns1:edgeSegment>
        </ns1:field>
        <ns1:road>
            <ns1:edge>north</ns1:edge>
        </ns1:road>
        <ns1:road>
            <ns1:edge>south</ns1:edge>
        </ns1:road>
        <ns1:road>
            <ns1:edge>west</ns1:edge>
        </ns1:road>
    </ns1:tile>
    <ns1:tile id="M" instances="2">
        <ns1:city>
            <ns1:edge>north</ns1:edge>
            <ns1:edge>west</ns1:edge>
            <ns1:pennant/>
        </ns1:city>
        <ns1:field>
            <ns1:edge>east</ns1:edge>
            <ns1:edge>south</ns1:edge>
        </ns1:field>
    </ns1:tile>
    <ns1:tile id="N" instances="3">
        <ns1:city>
            <ns1:edge>north</ns1:edge>
            <ns1:edge>west</ns1:edge>
        </ns1:city>
        <ns1:field>
            <ns1:edge>east</ns1:edge>
            <ns1:edge>south</ns1:edge>
        </ns1:field>
    </ns1:tile>
    <ns1:tile id="O" instances="2">
        <ns1:city>
            <ns1:edge>north</ns1:edge>
            <ns1:edge>west</ns1:edge>
            <ns1:pennant/>
        </ns1:city>
        <ns1:field>
            <ns1:edgeSegment>east-north</ns1:edgeSegment>
            <ns1:edgeSegment>south-west</ns1:edgeSegment>
        </ns1:field>
        <ns1:field>
            <ns1:edgeSegment>east-south</ns1:edgeSegment>
            <ns1:edgeSegment>south-east</ns1:edgeSegment>
        </ns1:field>
        <ns1:road>
            <ns1:edge>east</ns1:edge>
            <ns1:edge>south</ns1:edge>
        </ns1:road>
    </ns1:tile>
    <ns1:tile id="P" instances="3">
        <ns1:city>
            <ns1:edge>north</ns1:edge>
            <ns1:edge>west</ns1:edge>
        </ns1:city>
        <ns1:field>
            <ns1:edgeSegment>east-north</ns1:edgeSegment>
            <ns1:edgeSegment>south-west</ns1:edgeSegment>
        </ns1:field>
        <ns1:field>
            <ns1:edgeSegment>east-south</ns1:edgeSegment>
            <ns1:edgeSegment>south-east</ns1:edgeSegment>
        </ns1:field>
        <ns1:road>
            <ns1:edge>east</ns1:edge>
            <ns1:edge>south</ns1:edge>
        </ns1:road>
    </ns1:tile>
    <ns1:tile id="Q" instances="1">
        <ns1:city>
            <ns1:edge>north</ns1:edge>
            <ns1:edge>east</ns1:edge>
            <ns1:edge>west</ns1:edge>
            <ns1:pennant/>
        </ns1:city>
        <ns1:field>
            <ns1:edge>south</ns1:edge>
        </ns1:field>
    </ns1:tile>
    <ns1:tile id="R" instances="3">
        <ns1:city>
            <ns1:edge>north</ns1:edge>
            <ns1:edge>east</ns1:edge>
            <ns1:edge>west</ns1:edge>
        </ns1:city>
        <ns1:field>
            <ns1:edge>south</ns1:edge>
        </ns1:field>
    </ns1:tile>
    <ns1:tile id="S" instances="2">
        <ns1:city>
            <ns1:edge>north</ns1:edge>
            <ns1:edge>east</ns1:edge>
            <ns1:edge>west</ns1:edge>
            <ns1:pennant/>
        </ns1:city>
        <ns1:field>
            <ns1:edgeSegment>south-east</ns1:edgeSegment>
        </ns1:field>
        <ns1:field>
            <ns1:edgeSegment>south-west</ns1:edgeSegment>
        </ns1:field>
        <ns1:road>
            <ns1:edge>south</ns1:edge>
        </ns1:road>
    </ns1:tile>
    <ns1:tile id="T" instances="1">
        <ns1:city>
            <ns1:edge>north</ns1:edge>
            <ns1:edge>east</ns1:edge>
            <ns1:edge>west</ns1:edge>
        </ns1:city>
        <ns1:field>
            <ns1:edgeSegment>south-east</ns1:edgeSegment>
        </ns1:field>
        <ns1:field>
            <ns1:edgeSegment>south-west</ns1:edgeSegment>
        </ns1:field>
        <ns1:road>
            <ns1:edge>south</ns1:edge>
        </ns1:road>
    </ns1:tile>
    <ns1:tile id="U" instances="8">
        <ns1:field>
            <ns1:description>Field west of road</ns1:description>
            <ns1:edge>west</ns1:edge>
            <ns1:edgeSegment>north-west</ns1:edgeSegment>
            <ns1:edgeSegment>south-west</ns1:edgeSegment>
        </ns1:field>
        <ns1:field>
            <ns1:description>Field east of road</ns1:description>
            <ns1:edge>east</ns1:edge>
            <ns1:edgeSegment>north-east</ns1:edgeSegment>
            <ns1:edgeSegment>south-east</ns1:edgeSegment>
        </ns1:field>
        <ns1:road>
            <ns1:edge>north</ns1:edge>
            <ns1:edge>south</ns1:edge>
        </ns1:road>
